import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";
import Footer from "@/components/ui/footer";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ArogyaMitra",
  description: "Generated by create next app",
  icons: {
    icon: "/ArogyaMitra1.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  localStorage.setItem('theme', 'dark');
                  localStorage.removeItem('color-schema');
                  var s = document.createElement('style');
                  s.innerHTML = 'html{color-scheme:dark!important}html.dark{background:#262626!important}';
                  document.head.appendChild(s);
                  document.documentElement.classList.add('dark');
                  document.documentElement.style.colorScheme = 'dark';
                } catch (e) {}
              })()
            `,
          }}
        />
      </head>
      <body className={`${inter.className} bg-background text-foreground`}>
        <ThemeProvider
          attribute="class"
          forcedTheme="dark"
          enableSystem={false}
          disableTransitionOnChange
        >
          <ClerkProvider
            appearance={{ baseTheme: dark }}
            // Add these redirect configurations
            afterSignInUrl="/"
            afterSignUpUrl="/onboarding"
            signInFallbackRedirectUrl="/"
            signUpFallbackRedirectUrl="/onboarding"
          >
            <Header />
            <main className="min-h-screen">{children}</main>
            <Footer />
            <Toaster richColors />
          </ClerkProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
